# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CV for James Wrubel
name: James Wrubel
headshot: jwrubel_hs.jpg
pdf: jwrubel.pdf
headline: >
  I'm an entrepreneurially-minded multidisciplinary leader with 20+ years building, launching, and scaling internet-based initiatives.
description: >
  I bring a strong technical perspective to business challenges (and vice versa), and I'm uniquely experienced in rallying Software Development, UX, Product Management, Data Science, DevOps, Customer Service, and Digital Marketing teams toward business objectives. I can interpret stacktraces and corporate income statements equally well, and as a leader I have a passion for creating environments that foster diversity, creativity, learning and growth.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://james.wrubel.org" # the base hostname & protocol for your site

# collections
collections:
  - social
  - errata
  - publications
  - education
  - employment

# Build settings
markdown: kramdown
