# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CV for James Wrubel
given_name: James
family_name: Wrubel
headshot: jwrubel_hs.jpg
pdf: jwrubel.pdf
headline: >
  I'm an entrepreneurially-minded leader with 20+ years building, launching, and scaling technology businesses, mainly in deep learning (AI & machine learning), ed tech, and cybersecurity.
description: >
  I'm uniquely experienced in rallying Software Development, UX, Product Management, Data Science, DevOps, Customer Service, and Digital Marketing teams toward business objectives, and I'm equally comfortable at the command line and the board room. As a leader I have a passion for creating environments that foster diversity, creativity, learning and growth.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://james.wrubel.org" # the base hostname & protocol for your site

# analytics
analytics:
  tracking_id: UA-77429880-1
# social
social:
  location:
    icon: marker
    text: Pittsburgh, PA USA
  email:
    icon: mail outline
    text: jwrubel@gmail.com
    href: mailto:jwrubel@gmail.com
  www:
    icon: linkify
    text: james.wrubel.org
    href: http://james.wrubel.org
  twitter:
    icon: twitter
    text: "@jameswrubel"
    href: https://twitter.com/jameswrubel/
  github:
    icon: github
    text: jwrubel
    href: https://github.com/jwrubel/
  linkedin:
    icon: linkedin
    text: linkedin.com/in/jwrubel
    href: https://www.linkedin.com/in/jwrubel/
  medium:
    icon: medium
    text: "@jameswrubel"
    href: https://medium.com/@jameswrubel/
  angellist:
    icon: angellist
    text: jameswrubel
    href: https://angel.co/jameswrubel/

# collections
collections:
  - errata
  - publications
  - education
  - skills
  - employment

gems:
  - jekyll-assets

# layout settings
skill_rating_max: 3

# Build settings
markdown: kramdown
